# Generated by Django 5.2.4 on 2025-08-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0005_alter_prato_foto_prato_alter_prato_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='rendimento',
            field=models.CharField(max_length=100),
        ),
    ]
